/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author Widhian
 */
public class calc extends javax.swing.JFrame {

    public int op;
    public double num1, num2;
    
    /**
     * Creates new form calc
     */
    public calc() {
        initComponents();
        
        jRadioButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setType(java.awt.Window.Type.UTILITY);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {4};
        layout.rowHeights = new int[] {7};
        getContentPane().setLayout(layout);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        getContentPane().add(jTextField1, gridBagConstraints);

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(jButton1, gridBagConstraints);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jRadioButton1.setText("ON");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 5);
        getContentPane().add(jRadioButton1, gridBagConstraints);

        jButton2.setText("C");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(jButton2, gridBagConstraints);

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        getContentPane().add(jButton3, gridBagConstraints);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jRadioButton2.setText("OFF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        getContentPane().add(jRadioButton2, gridBagConstraints);

        jButton4.setText("7");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 5);
        getContentPane().add(jButton4, gridBagConstraints);

        jButton5.setText("8");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        getContentPane().add(jButton5, gridBagConstraints);

        jButton6.setText("9");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        getContentPane().add(jButton6, gridBagConstraints);

        jButton7.setText("-");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 10);
        getContentPane().add(jButton7, gridBagConstraints);

        jButton8.setText("4");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 5);
        getContentPane().add(jButton8, gridBagConstraints);

        jButton9.setText("5");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        getContentPane().add(jButton9, gridBagConstraints);

        jButton10.setText("6");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        getContentPane().add(jButton10, gridBagConstraints);

        jButton11.setText("x");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 10);
        getContentPane().add(jButton11, gridBagConstraints);

        jButton12.setText("1");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 5);
        getContentPane().add(jButton12, gridBagConstraints);

        jButton13.setText("2");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        getContentPane().add(jButton13, gridBagConstraints);

        jButton14.setText("3");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        getContentPane().add(jButton14, gridBagConstraints);

        jButton15.setText("/");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 10);
        getContentPane().add(jButton15, gridBagConstraints);

        jButton17.setText("=");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        getContentPane().add(jButton17, gridBagConstraints);

        jButton18.setText(".");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        getContentPane().add(jButton18, gridBagConstraints);

        jButton19.setText("0");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 5);
        getContentPane().add(jButton19, gridBagConstraints);

        setSize(new java.awt.Dimension(253, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void enable(){
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(true);
        
        jTextField1.setEnabled(true);
        
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton10.setEnabled(true);
        jButton11.setEnabled(true);
        jButton12.setEnabled(true);
        jButton13.setEnabled(true);
        jButton14.setEnabled(true);
        jButton15.setEnabled(true);
        jButton17.setEnabled(true);
        jButton18.setEnabled(true);
        jButton19.setEnabled(true);
    }
    
    public void disable(){
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(false);
        
        jTextField1.setEnabled(false);
        
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
        jButton10.setEnabled(false);
        jButton11.setEnabled(false);
        jButton12.setEnabled(false);
        jButton13.setEnabled(false);
        jButton14.setEnabled(false);
        jButton15.setEnabled(false);
        jButton17.setEnabled(false);
        jButton18.setEnabled(false);
        jButton19.setEnabled(false);
    }
    
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String txt      = jTextField1.getText();
        jTextField1.setText(txt + "1");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String txt      = jTextField1.getText();
        jTextField1.setText(txt + "2");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        String txt      = jTextField1.getText();
        jTextField1.setText(txt + "0");
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        String txt      = jTextField1.getText();
        jTextField1.setText(txt + "3");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String txt      = jTextField1.getText();
        jTextField1.setText(txt + "4");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String txt      = jTextField1.getText();
        jTextField1.setText(txt + "5");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String txt      = jTextField1.getText();
        jTextField1.setText(txt + "6");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String txt      = jTextField1.getText();
        jTextField1.setText(txt + "7");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String txt      = jTextField1.getText();
        jTextField1.setText(txt + "8");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String txt      = jTextField1.getText();
        jTextField1.setText(txt + "9");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        String txt      = jTextField1.getText();
        if(txt.contains("+")){
            String[] parts  = txt.split("\\+");
            String part     = parts[parts.length - 1];
            if(!part.contains(".")){
                jTextField1.setText(txt + ".");
            }
        } else if(txt.contains("-")){
            String[] parts  = txt.split("\\-");
            String part     = parts[parts.length - 1];
            if(!part.contains(".")){
                jTextField1.setText(txt + ".");
            }
        } else if(txt.contains("x")){
            String[] parts  = txt.split("x");
            String part     = parts[parts.length - 1];
            if(!part.contains(".")){
                jTextField1.setText(txt + ".");
            }
        } else if(txt.contains("/")){
            String[] parts  = txt.split("\\/");
            String part     = parts[parts.length - 1];
            if(!part.contains(".")){
                jTextField1.setText(txt + ".");
            }
        } else {
            if(!txt.contains(".")){
                jTextField1.setText(txt + ".");
            }
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String txt      = jTextField1.getText();
        
        if(txt.contains("+")){
            String[] parts  = txt.split("\\+");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 + this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "+");
            } else {
                jTextField1.setText(strHasil + "+");
            }            
        } else if(txt.contains("-")){
            String[] parts  = txt.split("\\-");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 - this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "+");
            } else {
                jTextField1.setText(strHasil + "+");
            }
        } else if(txt.contains("x")){
            String[] parts  = txt.split("x");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 * this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "+");
            } else {
                jTextField1.setText(strHasil + "+");
            }
        } else if(txt.contains("/")){
            String[] parts  = txt.split("\\/");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 / this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "+");
            } else {
                jTextField1.setText(strHasil + "+");
            }
        } else {
            this.num1 = Double.parseDouble(jTextField1.getText());
            jTextField1.setText(txt + "+");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String txt      = jTextField1.getText();
        
        if(txt.contains("+")){
            String[] parts  = txt.split("\\+");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 + this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "-");
            } else {
                jTextField1.setText(strHasil + "-");
            }            
        } else if(txt.contains("-")){
            String[] parts  = txt.split("\\-");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 - this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "-");
            } else {
                jTextField1.setText(strHasil + "-");
            }
        } else if(txt.contains("x")){
            String[] parts  = txt.split("x");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 * this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "-");
            } else {
                jTextField1.setText(strHasil + "-");
            }
        } else if(txt.contains("/")){
            String[] parts  = txt.split("\\/");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 / this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "-");
            } else {
                jTextField1.setText(strHasil + "-");
            }
        } else {
            this.num1 = Double.parseDouble(jTextField1.getText());
            jTextField1.setText(txt + "-");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String txt      = jTextField1.getText();
        
        if(txt.contains("+")){
            String[] parts  = txt.split("\\+");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 + this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "x");
            } else {
                jTextField1.setText(strHasil + "x");
            }            
        } else if(txt.contains("-")){
            String[] parts  = txt.split("\\-");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 - this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "x");
            } else {
                jTextField1.setText(strHasil + "x");
            }
        } else if(txt.contains("x")){
            String[] parts  = txt.split("x");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 * this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "x");
            } else {
                jTextField1.setText(strHasil + "x");
            }
        } else if(txt.contains("/")){
            String[] parts  = txt.split("\\/");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 / this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "x");
            } else {
                jTextField1.setText(strHasil + "x");
            }
        } else {
            this.num1 = Double.parseDouble(jTextField1.getText());
            jTextField1.setText(txt + "x");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        String txt      = jTextField1.getText();
        
        if(txt.contains("+")){
            String[] parts  = txt.split("\\+");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 + this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "/");
            } else {
                jTextField1.setText(strHasil + "/");
            }            
        } else if(txt.contains("-")){
            String[] parts  = txt.split("\\-");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 - this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "/");
            } else {
                jTextField1.setText(strHasil + "/");
            }
        } else if(txt.contains("x")){
            String[] parts  = txt.split("x");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 * this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "/");
            } else {
                jTextField1.setText(strHasil + "/");
            }
        } else if(txt.contains("/")){
            String[] parts  = txt.split("\\/");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 / this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0] + "/");
            } else {
                jTextField1.setText(strHasil + "/");
            }
        } else {
            this.num1 = Double.parseDouble(jTextField1.getText());
            jTextField1.setText(txt + "/");
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        disable();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        enable();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int length      = jTextField1.getText().length();
        int last        = jTextField1.getText().length() - 1;
        String newTxt;
        
        if(length > 0){
            StringBuilder back      = new StringBuilder(jTextField1.getText());
            back.deleteCharAt(last);
            newTxt                  = back.toString();
            jTextField1.setText(newTxt);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        String txt      = jTextField1.getText();
        
        if(txt.contains("+")){
            String[] parts  = txt.split("\\+");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 + this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0]);
            } else {
                jTextField1.setText(strHasil);
            }            
        } else if(txt.contains("-")){
            String[] parts  = txt.split("\\-");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 - this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0]);
            } else {
                jTextField1.setText(strHasil);
            }
        } else if(txt.contains("x")){
            String[] parts  = txt.split("x");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 * this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0]);
            } else {
                jTextField1.setText(strHasil);
            }
        } else if(txt.contains("/")){
            String[] parts  = txt.split("\\/");
            this.num1       = Double.parseDouble(parts[0]);
            this.num2       = Double.parseDouble(parts[1]);
            double hasil    = this.num1 / this.num2;
            String strHasil = Double.toString(hasil);
            String[] partsH = strHasil.split("\\.");
            double dig      = Double.parseDouble(partsH[1]);
            if(dig == 0){
                jTextField1.setText(partsH[0]);
            } else {
                jTextField1.setText(strHasil);
            }
        } else {
            jTextField1.setText(txt);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
